INSERT INTO Address (Street, Postal_code, City, Division, Country)
VALUES
('123 Main Street', 12345, 'Dhaka', 'Dhaka', 'Bangladesh'),
('123 Library Ln', 1234, 'Toronto', 'Ontario', 'Canada'),
('Polashi', 1216, 'Dhaka', 'Dhaka', 'Bangladesh'),
('456 KDA Avenue', 6100, 'Rajshahi', 'Rajshahi', 'Bangladesh'),
('78 Agrabad C/A', 4100, 'Chattogram', 'Chattogram', 'Bangladesh'),
('12 Dhanmondi Road 7A', 1209, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 CDA Avenue', 4000, 'Chattogram', 'Chattogram', 'Bangladesh'),
('10 Jessore Road', 9100, 'Khulna', 'Khulna', 'Bangladesh'),
('House 5, Road 10, Gulshan', 1212, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12/A Sector 4, Uttara', 1230, 'Dhaka', 'Dhaka', 'Bangladesh'),
('25 Mirpur Road', 1207, 'Dhaka', 'Dhaka', 'Bangladesh'),
('8 Banani Road 11', 1213, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Kazi Nazrul Islam Avenue', 1000, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Motijheel C/A', 1222, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Elephant Road', 1205, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Bashundhara R/A', 1229, 'Dhaka', 'Dhaka', 'Bangladesh'),
('56 Mohakhali DOHS', 1206, 'Dhaka', 'Dhaka', 'Bangladesh'),
('23 Tejgaon Industrial Area', 1208, 'Dhaka', 'Dhaka', 'Bangladesh'),
('67 Shantinagar', 1217, 'Dhaka', 'Dhaka', 'Bangladesh'),
('89 Farmgate', 1215, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Airport Road', 1204, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Dhanmondi Road 5', 1209, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Mohammadpur', 1207, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Lalmatia', 1207, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Baridhara', 1212, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Niketon', 1212, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Banani DOHS', 1206, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Rampura', 1219, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Malibagh', 1217, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Shyamoli', 1207, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Mirpur DOHS', 1216, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Khilgaon', 1219, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Badda', 1212, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Mohammadia Housing', 1207, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Bashabo', 1214, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Mugda', 1214, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Jatrabari', 1362, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Demra', 1361, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Kadamtali', 1360, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Sutrapur', 1100, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Kotwali', 1100, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Lalbagh', 1211, 'Dhaka', 'Dhaka', 'Bangladesh'),
('78 Hazaribagh', 1205, 'Dhaka', 'Dhaka', 'Bangladesh'),
('45 Kamrangirchar', 1211, 'Dhaka', 'Dhaka', 'Bangladesh'),
('90 Keraniganj', 1310, 'Dhaka', 'Dhaka', 'Bangladesh'),
('12 Savar', 1340, 'Dhaka', 'Dhaka', 'Bangladesh'),
('34 Tongi', 1710, 'Gazipur', 'Dhaka', 'Bangladesh'),
('78 Gazipur Sadar', 1700, 'Gazipur', 'Dhaka', 'Bangladesh'),
('45 Narayanganj', 1400, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('90 Sonargaon', 1410, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('12 Bandar', 1400, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('34 Fatullah', 1420, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('78 Siddhirganj', 1430, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('45 Rupganj', 1460, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('90 Araihazar', 1450, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('12 Munshiganj', 1500, 'Munshiganj', 'Dhaka', 'Bangladesh'),
('34 Tangail', 1900, 'Tangail', 'Dhaka', 'Bangladesh'),
('78 Mymensingh', 2200, 'Mymensingh', 'Dhaka', 'Bangladesh'),
('45 Kishoreganj', 2300, 'Kishoreganj', 'Dhaka', 'Bangladesh'),
('90 Netrokona', 2400, 'Netrokona', 'Dhaka', 'Bangladesh'),
('12 Jamalpur', 2000, 'Jamalpur', 'Dhaka', 'Bangladesh'),
('34 Sherpur', 2100, 'Sherpur', 'Dhaka', 'Bangladesh'),
('78 Kaliakair', 1750, 'Gazipur', 'Dhaka', 'Bangladesh'),
('45 Kapasia', 1740, 'Gazipur', 'Dhaka', 'Bangladesh'),
('90 Sreepur', 1741, 'Gazipur', 'Dhaka', 'Bangladesh'),
('12 Manikganj', 1800, 'Manikganj', 'Dhaka', 'Bangladesh'),
('34 Singair', 1810, 'Manikganj', 'Dhaka', 'Bangladesh'),
('78 Faridpur', 7800, 'Faridpur', 'Dhaka', 'Bangladesh'),
('45 Rajbari', 7700, 'Rajbari', 'Dhaka', 'Bangladesh'),
('90 Madaripur', 7900, 'Madaripur', 'Dhaka', 'Bangladesh'),
('12 Shariatpur', 8000, 'Shariatpur', 'Dhaka', 'Bangladesh'),
('34 Gopalganj', 8100, 'Gopalganj', 'Dhaka', 'Bangladesh'),
('78 Narsingdi', 1600, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('45 Palash', 1601, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('90 Raipura', 1602, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('12 Belabo', 1603, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('34 Monohardi', 1604, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('78 Shibpur', 1605, 'Narsingdi', 'Dhaka', 'Bangladesh'),
('45 Narayanganj Sadar', 1400, 'Narayanganj', 'Dhaka', 'Bangladesh'),
('90 Oxford Street', 10017, 'London', 'England', 'United Kingdom'),
('12 Rue de Rivoli', 75001, 'Paris', 'Île-de-France', 'France'),
('34 Alexanderplatz', 10178, 'Berlin', 'Berlin', 'Germany'),
('78 Wall Street', 10005, 'New York', 'New York', 'United States'),
('45 Ginza', 1040061, 'Tokyo', 'Tokyo', 'Japan'),
('90 Orchard Road', 238899, 'Singapore', 'Central Region', 'Singapore'),
('12 Connaught Place', 110001, 'New Delhi', 'Delhi', 'India'),
('34 Jalan Ampang', 50450, 'Kuala Lumpur', 'Kuala Lumpur', 'Malaysia'),
('78 Sydney Road', 2000, 'Sydney', 'New South Wales', 'Australia'),
('45 Robson Street', 0, 'Vancouver', 'British Columbia', 'Canada'),
('90 Sheikh Zayed Road', 123, 'Dubai', 'Dubai', 'UAE'),
('12 Corniche Road', 11564, 'Abu Dhabi', 'Abu Dhabi', 'UAE'),
('34 Sukhumvit Road', 10110, 'Bangkok', 'Bangkok', 'Thailand'),
('78 Bogyoke Aung San Road', 11181, 'Yangon', 'Yangon', 'Myanmar'),
('45 Jalan Sudirman', 10220, 'Jakarta', 'Jakarta', 'Indonesia'),
('90 Nathan Road', 999077, 'Hong Kong', 'Hong Kong', 'China'),
('12 Orchard Road', 238879, 'Singapore', 'Central Region', 'Singapore'),
('34 Ginza', 1040061, 'Tokyo', 'Tokyo', 'Japan'),
('Jorasanko Thakur Bari, Rabindra Sarani', 700007, 'Kolkata', 'West Bengal', 'India'),
('Bongaon, North 24 Parganas', 743235, 'Bongaon', 'West Bengal', 'India'),
('Devanandapur Village, Hooghly', 712149, 'Hooghly', 'West Bengal', 'India'),
('Kolkata University Press, College Street', 700073, 'Kolkata', 'West Bengal', 'India'),
('Sahitya Akademi, Rabindra Bhavan, Ferozeshah Road', 110001, 'New Delhi', 'Delhi', 'India'),
('National Book Trust, Vasant Kunj', 110070, 'New Delhi', 'Delhi', 'India'),
('Penguin Books India, Panchsheel Park', 110017, 'New Delhi', 'Delhi', 'India'),
('Oxford University Press India, YMCA Library Building, Jai Singh Road', 110001, 'New Delhi', 'Delhi', 'India');